@echo off

@echo WARNING VIRUS ATTACK!

@echo WARNING VIRUS ATTACK!

@echo WARNING VIRUS ATTACK!

@echo All Files Deleted. Reboot to Restore.

@echo Press Enter to Reboot

ping 1.1.1.1 -n 1 -w 5000 >NUL

@echo C: Drive Deleted

@echo WARNING! All Files Lost! Virus Detected

@echo Contact Administrator

@echo WARNING! FIREWALL BREACHED!

pause

@echo WARNING! System Shutdown in 5!

ping 1.1.1.1. -n 1 -w 1500>NUL

@echo WARNING! System Shutdown in 4!

ping 1.1.1.1 -n 1 -w 1500>NUL

@echo WARNING! System Shutdown in 3!

ping 1.1.1.1 -n 1 -w 1500>NUL

@echo WARNING! System Shutdown in 2!

ping 1.1.1.1 -n 1 -w 1500>NUL

@echo WARNING! System Shutdown in 1!

ping 1.1.1.1 -n 1 -w 1500>NUL

@echo Man are you easy to fool!

@echo Do you REALLY think I would make a virus to delete all files on your computer?

@echo Well, I might. But not this time.

@echo This time.

@echo THIS TIME.

@echo Press Enter to End

ping 1.1.1.1 -n 1 -w 4000 >NUL

@echo SIKE! Im deleting everything now!

@echo Now I will give you a REAL countdown!

pause

@echo DELETING ALL FILES IN 5

ping 1.1.1.1. -n 1 -w 1500>NUL

@echo DELETING ALL FILES IN 4

ping 1.1.1.1. -n 1 -w 1500>NUL

@echo DELETING ALL FILES IN 3

ping 1.1.1.1. -n 1 -w 1500>NUL

@echo DELETING ALL FILES IN 2

ping 1.1.1.1. -n 1 -w 1500>NUL

@echo DELETING ALL FILES IN 1

ping 1.1.1.1. -n 1 -w 1500>NUL

pause

color 2

:start

echo %random% %random% %random% %random% %random% %random% %random% %random% %random% %random% %random% %random% %random% %random%

goto start